### ISSUE TITLE
Scoring Improvement Idea

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#158]
We've talked a little about whether there is a better way to handle the scoring formula, and I have an idea! I spent a while trying to find a way to make `cut()` handle it for us, and it just. wasn't. working. So I started thinking about it from the beginning!

Ideally, we want our scoring solution to be a) transparent, b) efficient, and c) easy to update with scoring changes. So at the drawing board, I started wondering if maybe we don't have to use a function? Hear me out! I tried a couple different methods, and my suggestion is saving a super basic version of the scoring rubric in Excel, reading it in, and then inner joining based on the item to be scored. 

#### Illustration
Excel sheet with the simplified rubric:
![image](https://user-images.githubusercontent.com/43525277/115159821-d44ffa00-a049-11eb-8ced-cefcc0add4a1.png)

basic code to execute scoring:
```
scoring_rubric <- read_excel(file.choose()) %>%
  mutate(maximum = as.double(maximum),
         minimum = as.double(minimum))

scoring <- pe_exits_to_ph_with_percent  %>%
  inner_join(scoring_rubric %>%
               filter(metric == "exits_to_ph"), 
             by = "ProjectType") %>%
  filter(if_else(goal_type == "max",
                 minimum <= ExitsToPHPercent &
                   maximum > ExitsToPHPercent,
                 minimum < ExitsToPHPercent &
                   maximum >= ExitsToPHPercent))
```

#### Benefits
This basic scoring structure could literally be copied for each metric, because the min/max control in the Excel file combined with the `if_else()` evaluation lets you use the same structure for metrics we want to maximize and minimize. No need to separate out by program types, because that's what you're joining on. It doesn't take long to run, because your cross join is only creating 2-4x the original rows and the join doesn't happen until we're already at the program level. It's really easy to update, because you just make the Excel file match the rubric! I also think being able to label each row with the name of the metric instead of having to use the scoring structure might make it easier to read.

**Comment by gwenbeebe** [comment]
Minor note--if we move forward with this, we'll probably want to impute a temporary score of zero for any programs with no qualifying individuals to prevent them being filtered out in the score selection process.

**Comment by gwenbeebe** [comment]
[scoring_test.xlsx](https://github.com/COHHIO/COHHIO_HMIS/files/6333181/scoring_test.xlsx)

**Comment by kiadso** [comment]
Hi, finally had a sec to review the PR and I probably missed where the rubric.xlsx is? I think we could probably store it in public_data/ since it doesn't have client-level data in it. Anyway, if you want to add the doc to a PR and the file-path changes that come with that, that would be cool, or equally good would be just getting me the workbook and I can set that up.
