### ISSUE TITLE
COVID Yes/No Duplication

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#78]
All clients with a COVID assessment entered are currently being marked as Needs Isolation/Quarantine on the prioritization list because replace_yes_no() is applied to this assessment twice. The first application begins at line 417 in 00_get_Export_and_ART, and the second applications begins at line 202 in 08_Active_List. 

The function replace_yes_no() can't translate the binary variable it creates, so when run twice it changes all fields to 1. I commented code in the COVID section of 00_get_Export_and_ART as shown below, and all four possible levels appeared in the prioritization list in the correct order. Another option might be extending replace_yes_no() to accept binary variables.

```
# COVID-19 ----------------------------------------------------------------
  
covid19 <-
  read_xlsx(paste0(directory, "/RMisc2.xlsx"), sheet = 6) %>%
  mutate(
    COVID19AssessmentDate = ymd(as.Date(COVID19AssessmentDate,
                                        origin = "1899-12-30")),
    ContactWithConfirmedDate = ymd(as.Date(ContactWithConfirmedDate,
                                           origin = "1899-12-30")),
    ContactWithUnderInvestigationDate = ymd(
      as.Date(ContactWithUnderInvestigationDate,
              origin = "1899-12-30")
    ),
    TestDate = ymd(as.Date(TestDate,
                           origin = "1899-12-30")),
    DateUnderInvestigation = ymd(as.Date(DateUnderInvestigation,
                                         origin = "1899-12-30"))#,
    # Tested = replace_yes_no(Tested),
    # UnderInvestigation = replace_yes_no(UnderInvestigation),
    # ContactWithConfirmedCOVID19Patient = replace_yes_no(
    #   ContactWithConfirmedCOVID19Patient
    # ),
    # ContactWithUnderCOVID19Investigation = replace_yes_no(
    #   ContactWithUnderCOVID19Investigation
    # )
  ) #%>%
  # mutate_at(vars(matches("Symptom")), replace_yes_no) %>%
  # mutate_at(vars(matches("HealthRisk")), replace_yes_no)
```

**Comment by kiadso** [comment]
I fixed this by removing all the mutate arguments from the 08_ActiveList.R. This is a thing I caused by (incompletely) moving some logic up in the flow to prevent having to use the same code too many times. In this case, I added it upstream (to the 00_get_Export_and_ART script) but didn't remove it from the ActiveList one. Should be in effect tomorrow!
