### ISSUE TITLE
Clarifying HoH Correction Logic

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#83]
It looks like we might have an unnecessary line of code in this part of the 08_Active_List head of household correction logic?

```
168	# merging the "corrected" hohs back into the main dataset with a flag, then
169	# correcting the RelationshipToHoH
170	hohs <- active_list %>%
171	  left_join(Adjusted_HoHs,
172	            by = c("HouseholdID", "PersonalID", "EnrollmentID")) %>%
173	  mutate(RelationshipToHoH = if_else(correctedhoh == 1, 1, RelationshipToHoH)) %>%
174	  select(PersonalID, HouseholdID, correctedhoh)
```

At line 173 we're modifying the RelationshipToHoH column, but in line 174 we don't select RelationshipToHoH as one of our kept columns. If we don't want to keep it I don't think we need to modify it and might be able to drop line 173.

If we do want to keep it, though, I also want to flag that at a glance that line looks like it's updating the RelationshipToHoH column to 1 if the correctedhoh column is 1 and keeping the original value otherwise. However, if_else can't interpret NAs with ==, so we're actually setting the RelationshipToHoH to NA for every row where correctedhoh is NA. If that isn't what we're trying to do, we could change that line to `mutate(RelationshipToHoH = if_else(correctedhoh %in% 1, 1, RelationshipToHoH))`

**Comment by kiadso** [comment]
I think that mutate() should be affecting correctedhoh instead of RelationshipToHoH! So line 173 should be:
`mutate(corrected hoh = if_else(correctedhoh == 1, 1, RelationshipToHoH)) %>%`

**Comment by kiadso** [comment]
I think my proposed solution will cause issues further down in the script though, so that will need some working. Let me know if you would like me to take care of it upstream.

**Comment by gwenbeebe** [comment]
When you talk about further down, are you thinking about 529-540? I'm starting to think we might want a whole new column, but I'm not sure where in the script to put it. When we fix head of household errors, we're pulling out households with multiple heads and also those with no heads. What we have is working for the latter, but isn't quite right for the former. 

By line 536 we have two columns--one for original head of household status and another for flagging those that have been designated heads of household in households with errors. We say to use the flag if it exists, but otherwise use the original relationship. Only the person we chose as the head of household has a flag, though, so using the original relationship for other household members will recreate the issue if the original error was that too many people were listed as the head of household.

It doesn't feel terribly elegant, but I'm thinking the way to go might be joining `Adjusted_HoHs` back to `HHIDs_with_bad_dq` and setting `correctedhoh` to 0 if it is not 1 in `Adjusted_HoHs`, and then joining that table to `hohs`. That way we could safely use any existing value in the `correctedhoh`  column and use the `hoh` value otherwise, and just update the data quality flags to read any non-`NA` value in the `correctedhoh`  column as a household error. What do you think?

```
529	active_list <- active_list %>%
530	  mutate(
531	    HH_DQ_issue = if_else(
532	      correctedhoh == 1 & !is.na(correctedhoh),
533	      1,
534	      0
535	    ),
536	    HoH_Adjust = case_when(correctedhoh == 1 ~ 1,
537	                           is.na(correctedhoh) ~ hoh)
538	  ) %>%
539	  filter(HoH_Adjust == 1) %>%
540	  select(-correctedhoh, -RelationshipToHoH, -hoh, -HoH_Adjust)
```
