### ISSUE TITLE
Modify cohorts.R so that the summary_dfs are deduplicated

### ISSUE THREAD

**Issue by kiadso** [COHHIO/COHHIO_HMIS#84]
Description by GB: the household counts in 00_cohorts are duplicated, so if a client exits and re-enters program multiple times in a reporting period they will be counted each time.

Discussion on Slack: this should be fixed in the cohorts script.

**Comment by gwenbeebe** [comment]
We can close this, it was addressed by #103

**Comment by kiadso** [comment]
Thank you!
