### ISSUE TITLE
Questions about SinglyChronic Logic

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#86]
I have two questions about this SinglyChronic logic:

- At line 444 we're checking to see whether a year has passed between the homelessness date and their entry date. If they are in a literally homeless project, perhaps we should be comparing that homelessness date to today? I'm thinking of a person who enters the unsheltered provider when they're at 11 months, but remain on that list beyond the one year mark.

- We might want to consider updating line 448 to 
`(TimesHomelessPastThreeYears == 1 | TimesHomelessPastThreeYears == 4) &`
to capture the possibility of users entering the correct numbers of months but perhaps not the correct start date. It isn't a big change--I'm only seeing 14 clients that would be considered chronic after making this adjustment that are not currently considered chronic--but I wanted to note it.

```
437	singly_chronic <-
438	  active_list %>%
439	  left_join(smallEnrollment,
440				by = c("PersonalID",
441					   "EnrollmentID",
442					   "HouseholdID")) %>%
443	  mutate(SinglyChronic =
444			   if_else(((ymd(DateToStreetESSH) + days(365) <= ymd(EntryDate) &
445						   !is.na(DateToStreetESSH)) |
446						  (
447							MonthsHomelessPastThreeYears %in% c(112, 113) &
448							  TimesHomelessPastThreeYears == 4 &
449							  !is.na(MonthsHomelessPastThreeYears) &
450							  !is.na(TimesHomelessPastThreeYears)
451						  )
452			   ) &
453				 DisablingCondition == 1 &
454				 !is.na(DisablingCondition), 1, 0))
```

**Comment by kiadso** [comment]
To the first question- I think you're right, and the Aged Into Chronicity df is downstream of this, so it is probably not finding all the Aged In clients because of this. 
The second question- can you share one of the Client IDs of the 14 who are showing so I can see what you mean?

**Comment by gwenbeebe** [comment]
Sure. I'm looking at folks like 233050, where the entry data is inconsistent but at least some of it (the times homeless and number of months homeless) indicates length of time that would qualify as chronic.

**Comment by kiadso** [comment]
The HUD definition requires that Months and Times homeless have to be 4 or more occasions totaling 12 months over 3 years. So even if the 12 months over 3 years is met, if the # of occasions over 3 years isn't met, the client doesn't meet the definition. The Approximate Date Homeless through today is gauging whether there's a 12 month *consecutive* episode of homelessness, so the number of months could truthfully exceed the months represented in the Approx Date Homeless - today period of time. So from my reading of that client's data, they should not be considered chronic.

**Comment by gwenbeebe** [comment]
The definition allows for either four or more occasions totaling at least one year or at least a year of consecutive homelessness, which is why I would have flagged this one. If they are currently homeless, have only been homeless once in the last three years, and have a total of over 12 months of homelessness in the last three years, then by definition all of that has to be continuous? Otherwise they must have had multiple episodes instead of the one that's listed here. So either the start date or the number of episodes is wrong, but one of them definitely is. Might be worth a DQ flag?
