### ISSUE TITLE
"Eligible For PSH" could be extended

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#96]
The documentation for the "Eligible for PSH" column on the prioritization list says:

>**Eligible for PSH:**
>If you would like to filter for households eligible for PSH, enter "Yes" in the column search in the Eligible for PSH column. If there is a "Yes" there, it means someone in the household has a qualifying disability.

There are just over 200 folks on the priority list with differing disability statuses between 1.3 (subassessment) and 3.08 (yes/no dropdown), with about a hundred of those people who could be marked yes based on 1.3 but are not currently because of their 3.08 response. Based on that additional information, it could make sense to include them as potentially eligible for PSH.

Additionally, the [HUD definition](https://www.govinfo.gov/content/pkg/FR-2015-12-04/pdf/2015-30473.pdf) of chronic homelessness says that receiving disability income can be considered verification of a disability for the purposes of determining chronic homelessness. We know that not everyone who receives disability self-identifies as disabled, and because HMIS data is largely self-reported, that can cause discrepancies. If we wanted to mark these people as potentially PSH eligible as well, that would bring us up to ~240 mismatches, including ~150 people who are not currently marked eligible but could be.

To look at all this, you can just paste the following code at the end of 08_ script. The `D_Disability` column looks at 1.3, and `I_Disability` looks at 4.02.

```
disability_disagreement <- Disabilities %>%
  group_by(EnrollmentID) %>%
  mutate(D_Disability = if_else(DisabilityResponse == 1 &
                                   IndefiniteAndImpairs != 0, 1, 0),
         D_Disability = max(D_Disability)) %>%
  select(EnrollmentID, D_Disability) %>%
  distinct() %>%
  inner_join(Enrollment %>%
               select(
                 EnrollmentID, 
                 PersonalID, 
                 RelationshipToHoH, 
                 DisablingCondition, 
                 ProjectName,
                 EntryDate, 
                 ExitDate), 
             by = "EnrollmentID") %>%
  left_join(IncomeBenefits %>%
              filter(SSDI == 1 |
                       VADisabilityService == 1 |
                       VADisabilityNonService == 1 |
                       PrivateDisability == 1) %>%
              select(EnrollmentID) %>%
              distinct() %>%
              mutate(I_Disability = 1)
            , by = "EnrollmentID") %>%
  filter((D_Disability != DisablingCondition &
         !(D_Disability == 0
           & DisablingCondition %in% c(8, 9, 99))) |
           (DisablingCondition != 1 &
              !is.na(I_Disability))) %>%
  select(EnrollmentID, 
         PersonalID, 
         DisablingCondition, 
         D_Disability,
         I_Disability,
         ProjectName, 
         RelationshipToHoH,
         EntryDate,
         ExitDate) %>%
  mutate(PersonalID = as.character(PersonalID))

error_on_active <- disability_disagreement %>%
  inner_join(active_list, by = "PersonalID")

length(unique(error_on_active$PersonalID))
```

**Comment by kiadso** [comment]
Ah, yes, this is true. I think this is worth adding. Do you want me to take this code and incorporate it or do you want to do a PR? Thank you so much for thinking about this and coding it out.

**Comment by gwenbeebe** [comment]
I can do it! Question--do you think we should add this just to the eligible for PSH logic, or should it be all the way at the top when we're figuring out whether to flag folks as having a disability? That would extend their chronic determination as well, so I wanted to check.

**Comment by gwenbeebe** [comment]
Per our conversation today, I will set up a parallel disabling condition column with this logic in the script that we can use to calculate the Eligible for PSH column without changing the chronic logic at all.
